# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 06:55
from __future__ import unicode_literals

import api.models.self_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, verbose_name='用户邮箱')),
                ('award', models.CharField(default='0.00', max_length=32, verbose_name='奖励金额')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')),
                ('status', models.IntegerField(choices=[(0, '待处理'), (1, '待发送奖励邮件'), (2, '已处理')], default=0, verbose_name='漫画当前状态')),
                ('fbd_id', models.IntegerField(unique=True, verbose_name='意见反馈详情ID')),
            ],
            options={
                'verbose_name_plural': '意见反馈',
            },
            bases=(models.Model, api.models.self_model.Model),
        ),
        migrations.CreateModel(
            name='FeedBackDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, verbose_name='用户邮箱')),
                ('title', models.CharField(max_length=100, verbose_name='意见主题')),
                ('system', models.CharField(blank=True, max_length=16, null=True, verbose_name='操作系统')),
                ('content', models.TextField(verbose_name='意见内容')),
                ('picture', models.FileField(blank=True, null=True, upload_to='uploads/feedback', verbose_name='截图')),
            ],
            options={
                'verbose_name_plural': '意见详细信息',
            },
            bases=(models.Model, api.models.self_model.Model),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_id', models.IntegerField(verbose_name='漫画ID')),
                ('email', models.CharField(max_length=64, verbose_name='用户邮箱')),
                ('chap_id', models.IntegerField(verbose_name='章节ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '消费信息',
            },
            bases=(models.Model, api.models.self_model.Model),
        ),
        migrations.CreateModel(
            name='PurchaseAndFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, verbose_name='用户邮箱')),
                ('com_id', models.IntegerField(verbose_name='漫画ID')),
                ('status', models.IntegerField(choices=[(0, '购买'), (1, '收藏')], default=0, verbose_name='当前状态')),
            ],
            options={
                'verbose_name_plural': '用户购买与收藏漫画',
            },
            bases=(models.Model, api.models.self_model.Model),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(max_length=128, unique=True, verbose_name='交易ID')),
                ('email', models.CharField(max_length=64, verbose_name='用户邮箱')),
                ('platform', models.CharField(max_length=64, verbose_name='充值渠道')),
                ('gmv', models.CharField(max_length=32, verbose_name='交易金额')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pay_time', models.DateTimeField(default=None, null=True, verbose_name='支付时间')),
                ('status', models.IntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '已过期')], default=0, verbose_name='当前支付状态')),
            ],
            options={
                'verbose_name_plural': '交易记录',
            },
            bases=(models.Model, api.models.self_model.Model),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, unique=True, verbose_name='用户邮箱')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='昵称')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='uploads/avatar', verbose_name='头像')),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True, verbose_name='性别')),
                ('wallet_ios', models.CharField(default='0.00', max_length=32, verbose_name='钱包(ios)')),
                ('wallet_android', models.CharField(default='0.00', max_length=32, verbose_name='钱包(android)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_online', models.DateTimeField(auto_now=True, verbose_name='上次登录时间')),
                ('login_lock', models.BooleanField(default=False, verbose_name='登录锁')),
                ('bind', models.CharField(blank=True, max_length=100, null=True, verbose_name='第三方绑定ID')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
            bases=(models.Model, api.models.self_model.Model),
        ),
    ]
