# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=0, verbose_name='是否在线'),
        ),
    ]
