# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.IntegerField(choices=[(0, '待处理'), (1, '已处理')], default=0, verbose_name='漫画当前状态'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gmv',
            field=models.CharField(max_length=32, verbose_name='交易金额($)'),
        ),
    ]
