# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 09:34
from __future__ import unicode_literals

import api.models.self_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_id', models.IntegerField(verbose_name='漫画ID')),
                ('category', models.IntegerField(default=0, verbose_name='漫画分类')),
            ],
            options={
                'verbose_name': '分类信息',
            },
            bases=(models.Model, api.models.self_model.Model),
        ),
        migrations.CreateModel(
            name='ComicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_id', models.IntegerField(unique=True, verbose_name='漫画ID')),
                ('my_com_cover_img', models.FilePathField(blank=True, null=True, path='/Users/grave/Desktop/work/comics/media/<django.db.models.fields.IntegerField>', verbose_name='漫画封面')),
                ('free_chapter', models.IntegerField(default=0, verbose_name='免费章节数')),
                ('total_chapter', models.IntegerField(default=0, verbose_name='已有章节数')),
                ('download', models.BigIntegerField(default=0, verbose_name='下载量')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.IntegerField(default=1002, verbose_name='漫画当前状态')),
                ('category', models.IntegerField(default=0, verbose_name='漫画分类')),
            ],
            options={
                'verbose_name': '漫画信息',
            },
            bases=(models.Model, api.models.self_model.Model),
        ),
        migrations.CreateModel(
            name='ImgResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_id', models.IntegerField(verbose_name='漫画ID')),
                ('chap_id', models.IntegerField(verbose_name='章节ID')),
                ('price', models.CharField(default=0.0, max_length=32, verbose_name='章节单价')),
                ('chap_cover_img', models.FilePathField(blank=True, null=True, path='/Users/grave/Desktop/work/comics/media/<django.db.models.fields.IntegerField>/<django.db.models.fields.IntegerField>', verbose_name='章节封面')),
                ('my_title', models.CharField(max_length=100, null=True, verbose_name='章节名称')),
                ('my_img_list_path', models.CharField(max_length=32, null=True, verbose_name='章节图片路径')),
            ],
            options={
                'verbose_name': '漫画内容',
            },
            bases=(models.Model, api.models.self_model.Model),
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_id', models.IntegerField(unique=True, verbose_name='漫画ID')),
                ('my_title', models.CharField(max_length=100, null=True, verbose_name='漫画名')),
                ('my_author', models.CharField(max_length=100, null=True, verbose_name='漫画作者')),
                ('my_subtitle', models.TextField(null=True, verbose_name='漫画副标题')),
                ('my_introduction', models.TextField(null=True, verbose_name='漫画简介')),
            ],
            options={
                'verbose_name': '漫画检索',
            },
            bases=(models.Model, api.models.self_model.Model),
        ),
    ]
