# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '分类信息'},
        ),
        migrations.AlterModelOptions(
            name='comicinfo',
            options={'verbose_name_plural': '漫画信息'},
        ),
        migrations.AlterModelOptions(
            name='imgresource',
            options={'verbose_name_plural': '漫画内容'},
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': '漫画检索'},
        ),
        migrations.AlterField(
            model_name='comicinfo',
            name='category',
            field=models.IntegerField(default=0, verbose_name='漫画当前分类'),
        ),
    ]
