# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminx', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databackup',
            options={'verbose_name_plural': '备份'},
        ),
        migrations.AlterField(
            model_name='mangaupload',
            name='name',
            field=models.CharField(max_length=64, verbose_name='文件名 '),
        ),
    ]
