# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 02:55
from __future__ import unicode_literals

import api.models.self_model
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('adminx', '0002_auto_20181009_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, '今日充值'), (1, '昨日充值'), (2, '本月充值'), (3, '本季充值'), (4, '历史充值')],
                                             verbose_name='时间', unique=True)),
                ('income', models.CharField(max_length=32, verbose_name='收入')),
                ('paid_order', models.IntegerField(verbose_name='已支付订单数')),
                ('no_paid_order', models.IntegerField(verbose_name='未支付订单数')),
                ('total_order', models.IntegerField(verbose_name='全部订单数')),
            ],
            options={
                'verbose_name_plural': '简要订单统计',
            },
            bases=(models.Model, api.models.self_model.Model),
        ),
        migrations.CreateModel(
            name='OrderStatisticDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期', unique=True)),
                ('income', models.CharField(max_length=8, verbose_name='收入')),
                ('expect_income', models.CharField(max_length=8, verbose_name='期望收入')),
                ('paid_order', models.IntegerField(verbose_name='已支付订单数')),
                ('no_paid_order', models.IntegerField(verbose_name='未支付订单数')),
                ('total_order', models.IntegerField(verbose_name='全部订单数')),
            ],
            options={
                'verbose_name_plural': '详细订单统计',
            },
            bases=(models.Model, api.models.self_model.Model),
        ),
    ]
