# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminx', '0003_orderstatistic_orderstatisticdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatistic',
            name='expired_order',
            field=models.IntegerField(default=0, verbose_name='已失效订单数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderstatisticdetail',
            name='expired_order',
            field=models.IntegerField(default=0, verbose_name='已失效订单数'),
            preserve_default=False,
        ),
    ]
