# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminx', '0004_auto_20181009_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatistic',
            options={'ordering': ['name'], 'verbose_name_plural': '简要订单统计'},
        ),
        migrations.AlterField(
            model_name='orderstatistic',
            name='income',
            field=models.CharField(max_length=32, verbose_name='收入($)'),
        ),
        migrations.AlterField(
            model_name='orderstatistic',
            name='no_paid_order',
            field=models.IntegerField(verbose_name='待支付订单数'),
        ),
        migrations.AlterField(
            model_name='orderstatisticdetail',
            name='expect_income',
            field=models.CharField(max_length=8, verbose_name='期望收入($)'),
        ),
        migrations.AlterField(
            model_name='orderstatisticdetail',
            name='income',
            field=models.CharField(max_length=8, verbose_name='收入($)'),
        ),
        migrations.AlterField(
            model_name='orderstatisticdetail',
            name='no_paid_order',
            field=models.IntegerField(verbose_name='待支付订单数'),
        ),
    ]
